const Data = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    year: "2018 - 2022",
    title: "Mount Kenya University",
    desc: "BSc Economics and Finance",
  },
  {
    id: 2,
    category: "education",
    icon: "icon-graduation",
    year: "2022 - 2022",
    title: "Professional Certification - Moringa School",
    desc: "Software Engineering : Tools Covered: Vanilla JavaScript, HTML, CSS, Unix/Linux CLI, React JS / Redux / JSX / Vite, Version Control, Figma Designing, Ruby on Rails, SQL / PostgreSQL, DOM Manipulation, App deployment / Cloud Hosting,UI/UX",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "2020 - 2021",
    title: "Professional Certification - Moringa School",
    desc: " Data Science : Supervised & Unsupervised Learning, Advanced Regression i.e. Linear, Logistic, Ridge, Lasso, Polynomial, Elastic-net models, etc, Classification and Regression Trees (CART): Decision Trees. Neural Networks: RNN, ANN, CNN, MLP, Tensor flow. R for Data Science: Data wrangling and EDA in R, Association Analysis, Clustering Techniques, etc. Teamwork and Collaboration. Project presentation and Documentation.",
  },
  {
    id: 4,
    category: "experience",
    icon: "icon-briefcase",
    year: "2022 - present",
    title: "Data Scientist - Zamara",
    desc: "Offering consultancy services in the data science space",
  },
  {
    id: 5,
    category: "experience",
    icon: "icon-briefcase",
    year: "22022 - 2023",
    title: "Machine Leaning Engineer - United States of Africa",
    desc: "Develop machine learning applications according to requirements, Research and implement appropriate ML algorithms and tools for NLP tasks. Train the developed model and run evaluation experiments",
  },
  {
    id: 6,
    category: "experience",
    icon: "icon-briefcase",
    year: "2021 - 2022",
    title: "Data Scientist - Bidco- Africa",
    desc: "    Business intelligence to the top management for an eye-bird view of the business performance. Automation Processes using Python, Power BI, R, Microsoft Flows(Microsoft Power Automate).Geospatial routing using Kepplers, Mapbox, Aspose, My maps. SAP data validation through BobJ. Sales People Management and product movement checks.This role included: - Business intelligence to the top management for an eye-bird view of the business performance. - Automation Processes using Python, Power BI, R, Microsoft Flows(Microsoft Power Automate) - Geospatial routing using Kepplers, Mapbox, Aspose, My maps. - SAP data validation through BobJ - Sales People Management and product movement checks.",
  },
  {
    id: 7,
    category: "experience",
    icon: "icon-briefcase",
    year: "2019 - 2021",
    title: "Data Scientist - Upwork",
    desc: "Data visualization projects to provide intelligence, Build data models such as predictive models, Recommender engines, Research-based on the client's needs and the project needs, Consulting",
  },
  {
    id: 8,
    category: "experience",
    icon: "icon-briefcase",
    year: "2022 - present",
    title: "Economist - The National Treasury of Kenya",
    desc: "    Research economic issues. Conduct surveys and collect data. Analyze data using mathematical models, statistical techniques, and software.Present research results in reports, tables, and charts. Interpret and forecast market trends ",
  },
  {
    id: 9,
    category: "experience",
    icon: "icon-briefcase",
    year: "2021 - 2021",
    title: "Data science consultant- Saharadatatech",
    desc: "Involved in educating clients on varying aspects of data and modern technology. More specifically; Building up customers' analytics skills. Data competencies. Better structure the machinations and workings of their business to get optimal intelligence from the metadata points.",
  },
  {
    id: 10,
    category: "experience",
    icon: "icon-briefcase",
    year: "2019 - 2020",
    title: "Data Analyst Facilitator - Peer2Peer University",
    desc: "The main roles as a facilitator were; Provide interactive classes. Build structured content for the students. Formulate real time-based projects. Measure and evaluate the performances",
  },
];

export default Data;
