const Data = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    year: "2018 - 2022",
    title: "Mount Kenya University",
    desc: "BSc Economics and Finance",
  },
  {
    id: 2,
    category: "education",
    icon: "icon-graduation",
    year: "2022 - 2022",
    title: "Professional Certification - Moringa School",
    desc: "Software Engineering ",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "2020 - 2021",
    title: "Professional Certification - Moringa School",
    desc: " Data Science",
  },
  {
    id: 4,
    category: "experience",
    icon: "icon-briefcase",
    year: "2022 - present",
    title: "Data Scientist - Zamara",
    desc: "Offering consultancy services in the data science space",
  },
  {
    id: 5,
    category: "experience",
    icon: "icon-briefcase",
    year: "22022 - 2023",
    title: "Machine Leaning Engineer - United States of Africa",
    desc: "Develop machine learning applications according to requirements",
  },
  {
    id: 6,
    category: "experience",
    icon: "icon-briefcase",
    year: "2021 - 2022",
    title: "Data Scientist - Bidco- Africa",
    desc: "Business intelligence to the top management for an eye-bird view of the business performance. ",
  },
  {
    id: 7,
    category: "experience",
    icon: "icon-briefcase",
    year: "2019 - 2021",
    title: "Data Scientist - Upwork",
    desc: "Research-based on the client's needs and the project needs, Consulting",
  },
  {
    id: 8,
    category: "experience",
    icon: "icon-briefcase",
    year: "2022 - present",
    title: "Economist - The National Treasury of Kenya",
    desc: "Research economic issues. Conduct surveys and collect data. ",
  },
  {
    id: 9,
    category: "experience",
    icon: "icon-briefcase",
    year: "2021 - 2021",
    title: "Data science consultant- Saharadatatech",
    desc: "Involved in educating clients on varying aspects of data and modern technology.",
  },
  {
    id: 10,
    category: "experience",
    icon: "icon-briefcase",
    year: "2019 - 2020",
    title: "Data Analyst Facilitator - Peer2Peer University",
    desc: "The main roles as a facilitator were; Provide interactive classes.",
  },
];

export default Data;
